name: Update TLDs
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wow-actions/download-upload@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          url: https://data.iana.org/TLD/tlds-alpha-by-domain.txt
          filename: tlds.txt
