name: Update TLDs
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  gettlds:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wow-actions/download-upload@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          url: https://data.iana.org/TLD/tlds-alpha-by-domain.txt
          filename: tlds.txt
  formatfile:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Replace linebreaks in file
        run: |
          sed '{:repl;N;$!brepl;s/\n/^\n||/g;}' "tlds.txt" > "blocklist.txt"
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add --all
          git commit -m "Update blocklist from latest TLDs file" -a
          git push -f
