name: Update TLDs
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  gettlds:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wow-actions/download-upload@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          url: https://data.iana.org/TLD/tlds-alpha-by-domain.txt
          filename: tlds.txt
  formatfile:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: jafin/gha-search-replace@0.2-alpha
        with:
          include: tlds.txt
          search: \r\n
          replace: ^\r\n@@||
